/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author willi
 */
public class FrmTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmTelaPrincipal
     */
    public FrmTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        itemUsuarioCadastrar = new javax.swing.JMenuItem();
        itemUsuarioAlterar = new javax.swing.JMenuItem();
        itemUsuarioExcluir = new javax.swing.JMenuItem();
        itemUsuarioPesquisar = new javax.swing.JMenuItem();
        menuAluno = new javax.swing.JMenu();
        itemAlunoCadastrar = new javax.swing.JMenuItem();
        itemAlunoAlterar = new javax.swing.JMenuItem();
        itemAlunoExcluir = new javax.swing.JMenuItem();
        itemAlunoPesquisar = new javax.swing.JMenuItem();
        menuAtividade = new javax.swing.JMenu();
        itemAtividadeCadastrar = new javax.swing.JMenuItem();
        itemAtividadeAlterar = new javax.swing.JMenuItem();
        itemAtividadeExcluir = new javax.swing.JMenuItem();
        itemAtividadePesquisar = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenu();
        itemCategoriaCadastrar = new javax.swing.JMenuItem();
        itemCategoriaAlterar = new javax.swing.JMenuItem();
        itemCategoriaExcluir = new javax.swing.JMenuItem();
        itemCategoriaPesquisar = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenu();

        jMenuItem7.setText("jMenuItem7");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jdpPrincipal);
        jdpPrincipal.setBounds(0, 0, 670, 420);

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user.png"))); // NOI18N
        menuUsuario.setText("Usuário");

        itemUsuarioCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user_add.png"))); // NOI18N
        itemUsuarioCadastrar.setText("Cadastrar");
        itemUsuarioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioCadastrarActionPerformed(evt);
            }
        });
        menuUsuario.add(itemUsuarioCadastrar);

        itemUsuarioAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user_edit.png"))); // NOI18N
        itemUsuarioAlterar.setText("Alterar");
        menuUsuario.add(itemUsuarioAlterar);

        itemUsuarioExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user_delete.png"))); // NOI18N
        itemUsuarioExcluir.setText("Excluir");
        menuUsuario.add(itemUsuarioExcluir);

        itemUsuarioPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/zoom.png"))); // NOI18N
        itemUsuarioPesquisar.setText("Pesquisar");
        menuUsuario.add(itemUsuarioPesquisar);

        jMenuBar1.add(menuUsuario);

        menuAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/group.png"))); // NOI18N
        menuAluno.setText("Aluno");

        itemAlunoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/group_add.png"))); // NOI18N
        itemAlunoCadastrar.setText("Cadastrar");
        menuAluno.add(itemAlunoCadastrar);

        itemAlunoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/group_edit.png"))); // NOI18N
        itemAlunoAlterar.setText("Alterar");
        itemAlunoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlunoAlterarActionPerformed(evt);
            }
        });
        menuAluno.add(itemAlunoAlterar);

        itemAlunoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/group_delete.png"))); // NOI18N
        itemAlunoExcluir.setText("Excluir");
        menuAluno.add(itemAlunoExcluir);

        itemAlunoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/zoom.png"))); // NOI18N
        itemAlunoPesquisar.setText("Pesquisar");
        itemAlunoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlunoPesquisarActionPerformed(evt);
            }
        });
        menuAluno.add(itemAlunoPesquisar);

        jMenuBar1.add(menuAluno);

        menuAtividade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/page.png"))); // NOI18N
        menuAtividade.setText("Atividade");

        itemAtividadeCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/page_add.png"))); // NOI18N
        itemAtividadeCadastrar.setText("Cadastrar");
        menuAtividade.add(itemAtividadeCadastrar);

        itemAtividadeAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/page_edit.png"))); // NOI18N
        itemAtividadeAlterar.setText("Alterar");
        menuAtividade.add(itemAtividadeAlterar);

        itemAtividadeExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/page_delete.png"))); // NOI18N
        itemAtividadeExcluir.setText("Excluir");
        menuAtividade.add(itemAtividadeExcluir);

        itemAtividadePesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/zoom.png"))); // NOI18N
        itemAtividadePesquisar.setText("Pesquisar");
        menuAtividade.add(itemAtividadePesquisar);

        jMenuBar1.add(menuAtividade);

        menuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder_page.png"))); // NOI18N
        menuCategoria.setText("Categoria");

        itemCategoriaCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder_add.png"))); // NOI18N
        itemCategoriaCadastrar.setText("Cadastrar");
        menuCategoria.add(itemCategoriaCadastrar);

        itemCategoriaAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder_edit.png"))); // NOI18N
        itemCategoriaAlterar.setText("Alterar");
        menuCategoria.add(itemCategoriaAlterar);

        itemCategoriaExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder_delete.png"))); // NOI18N
        itemCategoriaExcluir.setText("Excluir");
        menuCategoria.add(itemCategoriaExcluir);

        itemCategoriaPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/zoom.png"))); // NOI18N
        itemCategoriaPesquisar.setText("Pesquisar");
        menuCategoria.add(itemCategoriaPesquisar);

        jMenuBar1.add(menuCategoria);

        menuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/page_white_acrobat.png"))); // NOI18N
        menuRelatorio.setText("Relatorio");
        jMenuBar1.add(menuRelatorio);

        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/information.png"))); // NOI18N
        menuSobre.setText("Sobre");
        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 683, 484);
    }// </editor-fold>//GEN-END:initComponents

    private void itemUsuarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioCadastrarActionPerformed

       /* FrmFuncionario funcionario = new FrmFuncionario();
        
        jdpPrincipal.add(funcionario);
        
        funcionario.setVisible(true);
        
        */
    }//GEN-LAST:event_itemUsuarioCadastrarActionPerformed

    private void itemAlunoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlunoAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAlunoAlterarActionPerformed

    private void itemAlunoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlunoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAlunoPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAlunoAlterar;
    private javax.swing.JMenuItem itemAlunoCadastrar;
    private javax.swing.JMenuItem itemAlunoExcluir;
    private javax.swing.JMenuItem itemAlunoPesquisar;
    private javax.swing.JMenuItem itemAtividadeAlterar;
    private javax.swing.JMenuItem itemAtividadeCadastrar;
    private javax.swing.JMenuItem itemAtividadeExcluir;
    private javax.swing.JMenuItem itemAtividadePesquisar;
    private javax.swing.JMenuItem itemCategoriaAlterar;
    private javax.swing.JMenuItem itemCategoriaCadastrar;
    private javax.swing.JMenuItem itemCategoriaExcluir;
    private javax.swing.JMenuItem itemCategoriaPesquisar;
    private javax.swing.JMenuItem itemUsuarioAlterar;
    private javax.swing.JMenuItem itemUsuarioCadastrar;
    private javax.swing.JMenuItem itemUsuarioExcluir;
    private javax.swing.JMenuItem itemUsuarioPesquisar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu menuAluno;
    private javax.swing.JMenu menuAtividade;
    private javax.swing.JMenu menuCategoria;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
